# Generated by Django 6.0.5 on 2026-06-04 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal'), ('zelle', 'Zelle')], max_length=20)),
                ('display_name', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=150)),
                ('account_identifier', models.CharField(help_text='Account number, email, or phone', max_length=150)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('routing_number', models.CharField(blank=True, max_length=50)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('instructions', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='depositrequest',
            name='transfer_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_requests', to='wallet.transfermethod'),
        ),
    ]
