# Generated by Django 6.0.5 on 2026-05-08 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('change', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('change_percent', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('volume', models.CharField(blank=True, max_length=20)),
                ('market_cap', models.CharField(blank=True, max_length=20)),
                ('high_52w', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('low_52w', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('pe', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('dividend', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock')),
            ],
        ),
    ]
