# Generated by Django 6.0.5 on 2026-05-15 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['ticker']},
        ),
    ]
